- name: Install .Net 3.5 on 2016
  win_feature:
    name: NET-Framework-Core
    state: present
  when: ansible_distribution_major_version == "10"

- name: Install .Net 3.5 on 2012
  win_feature:
    name: NET-Framework
    state: present
  when: ansible_distribution_major_version == "6"
 
