- name: Install and Configure Windows SNMP
  hosts: all
  vars:
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: credssp
    ansible_winrm_kerberos_delegation: yes
  roles:
    - win_snmp
