- name: Add sysadmins group
  group:
    name: sysadmins
    gid: 400
    state: present


- name: Create hetroot
  user:
    name: hetroot
    group: sysadmins
    state: present

- name: Create snowcmdb
  user:
    name: snowcmdb
    state: present

- name: Add sysadmins to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sysadmins'
    line: '%sysadmins      ALL=(ALL)       NOPASSWD: ALL'

- name: Add snowcmdb to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^snowcmdb'
    line: 'snowcmdb        ALL=(root)      NOPASSWD: /usr/sbin/dmidecode,/usr/sbin/lsof'

- name: Install SNMP
  yum:
    name: net-snmp*

- name: Configure SNMP
  template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf

- name: Start and enable SNMP
  service:
    name: snmpd
    state: started
    enabled: yes

#- name: Download eVault Binary
#  get_url:
#    url:
#    dest:

- name: Extract the eVault Binary
  unarchive:
    src: /home/ec2-user/Evault-Agent-Linux-x64-8.00.6289b.tar
    dest: /tmp/evault-installer/
    remote_src: Yes

- name: Create eVault Web Config
  template:
    src: templates/web-registration.txt.j2
    dest: /tmp/evault-installer/web-registrations.txt

- name: Install eVault
  command: ./install.sh -force-defaults -web-registration=/tmp/evault-installer/web-registrations.txt
  args:
    chdir: /tmp/evault-installer/
    creates: /opt/BUAgent
