- name: Add sysadmins group
  group:
    name: sysadmins
    gid: 400
    state: present


- name: Create hetroot
  user:
    name: hetroot
    group: sysadmins
    state: present

- name: Create snowcmdb
  user:
    name: snowcmdb
    state: present

- name: Add sysadmins to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sysadmins'
    line: '%sysadmins      ALL=(ALL)       NOPASSWD: ALL'

- name: Add snowcmdb to sudoers
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^snowcmdb'
    line: 'snowcmdb        ALL=(root)      NOPASSWD: /usr/sbin/dmidecode,/usr/sbin/lsof'

- name: Install SNMP
  yum:
    name: net-snmp*

- name: Configure SNMP
  template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf

- name: Start and enable SNMP
  service:
    name: snmpd
    state: started
    enabled: yes

#- name: Download eVault Binary
#  get_url:
#    url:
#    dest:

- name: Extract the eVault Binary
  unarchive:
    src: /home/ec2-user/Evault-Agent-Linux-x64-8.00.6289b.tar
    dest: /tmp/
    remote_src: Yes

- name: Create eVault Web Config
  template:
    src: templates/web-registration.txt.j2
    dest: /tmp/Agent-Linux-x64-8.00.6289b/web-registrations.txt

- name: Install eVault
  command: ./install.sh -force-defaults -web-registration=/tmp/Agent-Linux-x64-8.00.6289b/web-registrations.txt
  args:
    chdir: /tmp/Agent-Linux-x64-8.00.6289b
    creates: /opt/BUAgent

#- name: Update Sudoers file for root

- name: Download Cloud Health BUAgent
  get_url:
    url: https://s3.amazonaws.com/remote-collector/agent/v14/install_cht_perfmon.sh
    dest: /tmp/install_cht_perfmon.sh
  when: "'amazon' in ansible_product_version"

- name: Change install_cht_perfmon.sh permissions
  file:
    path: /tmp/install_cht_perfmon.sh
    mode: 0755

- name: Install Cloud Health BUAgent
  command: ./install_cht_perfmon.sh 14 d0828869031db-431b-b3ff-4b98deb40627 aws
  args:
    chdir: /tmp
    #creates:
  when: "'amazon' in ansible_product_version"
