- name: Copy Server Support Directory
  win_copy:
    src: \\Sctermsrv01\d$\Server Support-DLM\Support
    dest: C:\
    remote_src: yes
    force: no

- name: Install 7zip
  win_package:
    path: C:\support\7-zip\7z1604-x64.msi
    product_id: 7-Zip
    arguments: /q
    state: present
    creates_path: C:\program files\7-zip\7z.exe

- name: Install Nxlog
  win_package:
    path: C:\support\nxlog\nxlog-ce-2.9.1716.msi 
    product_id: nxlog 
    arguments: /qr
    state: present
    creates_path: C:\program files (x86)\nxlog
  
