- name: Copy Server Support Directory
  win_copy:
    src: \\Sctermsrv01\d$\Server Support-DLM\Support
    dest: C:\
    remote_src: yes
    force: no

- name: Install 7zip
  win_package:
    path: C:\support\7-zip\7z1604-x64.msi
    product_id: 7-Zip
    arguments: /q
    state: present
    creates_path: C:\program files\7-zip\7z.exe

- name: Install Nxlog
  win_package:
    path: C:\support\nxlog\nxlog-ce-2.9.1716.msi
    product_id: nxlog
    arguments: /qr
    state: present
    creates_path: C:\program files (x86)\nxlog

- name: Update nxlog conf file
  win_template:
    src: templates/nxlog.conf.j2
    dest: C:\program files (x86)\nxlog\nxlog.conf
  notify: restart nxlog

- name: Install Evault software
  win_package:
    path: C:\Support\Evault\latest_Win_64bit\Agent-Windows-x64-8-31-7896.exe
    product_id: auto
    arguments: /s
    state: present
    creates_path: C:\Program Files\EVault Software

- name: Install CloudHealth Agent
  win_package:
    path: C:\support\Cloud Health Agent\CloudHealthAgent.exe
    product_id: auto
    arguments: /S /v"/l* install.log /qn CLOUDNAME=aws CHTAPIKEY=da1c44be-202d-4bf8-b74f-de7d821dbe65"
    state: present
  when: "'amazon' in ansible_bios_version"

- name: Install SEP
  win_package:
    path: C:\support\Sep Server Installs\x64\setup.exe
    product_id: auto
    arguments: /s
    state: present
    creates_path: C:\Program Files (x86)\Symantec\Symantec Endpoint Protection
  notify: restart server
