- name: Rename Computer
  win_domain_membership: 
    hostname: "{{ inventory_hostname }}"
    domain_admin_user: "{{ ansible_user }}"
    domain_admin_password: "{{ ansible_ssh_pass }}"
  register: rename

- name: Reboot if neccesary
  win_reboot:
  when: rename.reboot_required
