- name: Set Timezone
  win_timezone:
    timezone: "{{ timezones[location] }}"

- name: Set DNS servers
  win_dns_client:
    adapter_names: "*"
    ipv4_addresses:
      - "{{ dns_servers[location] }}"
  when: dns_servers[location] is defined

- name: Set pagefile size
  win_pagefile:
    initial_size: 0
    maximum_size: 0
    drive: C
    override: yes
    state: present
  register: setpagefile

- name: Reboot to reset Pagefile to zero
  win_reboot:
  when: setpagefile.changed

- name: Defrag harddrive
  win_defrag:
    freespace_consolidation: yes
    parallel: no
    priority: normal

- name: Set pagefile size
  win_pagefile:
    initial_size: "{{ ansible_memtotal_mb | int * 1.0 }}"
    maximum_size: "{{ ansible_memtotal_mb | int * 1.0 }}"
    drive: C
    override: yes
    state: present

- name: Rename Computer
  win_domain_membership:
    hostname: "{{ inventory_hostname }}"
    state: workgroup
    workgroup_name: WORKGROUP
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"

- name: Reboot
  win_reboot:

- name: Join Computer to domain
  win_domain_membership:
    hostname: "{{ inventory_hostname }}"
    state: domain
    dns_domain_name: companynet.org
    domain_admin_user: "{{ domain_admin_user }}"
    domain_admin_password: "{{ domain_admin_password }}"

- name: Reboot
  win_reboot:

- name: Pause for 4 mins
  pause:
    minutes: 4
