- name: Rename Computer
  win_domain_membership: 
    hostname: "{{ inventory_hostname }}"
    state: workgroup
    workgroup_name: workgroup
    domain_admin_user: "{{ ansible_user }}"
    domain_admin_password: "{{ ansible_ssh_pass }}"
  register: rename

- name: Reboot if neccesary
  win_reboot:
  when: rename.reboot_required

- name: Set pagefile size
  win_pagefile: 
    initial_size: "{{ ansible_memtotal_mb }}" * 1.5 
    maximum_size: "{{ ansible_memtotal_mb }}" * 1.5
    drive: C
    override: yes
    state: present
