    - name: Install Windows Updates
      win_updates: 
        category_names: "{{ catagories }}"
      register: winup

    - name: Reboot if neccesary
      win_reboot:
        shutdown_timeout_sec: 3600
        reboot_timeout_sec: 3600
      when: winup.reboot_required 
